Numpy-Numerical Python

1.Allows several Mathematical Operations

2.Faster operations

In [1]:
import numpy as np

List vs Numpy-Time Taken

In [1]:
from time import process_time

In [45]:
python_list=[i for i in range(100)]
print(python_list)
start_time=process_time()
python_list=[i+5 for i in python_list]
print(python_list)
end_time=process_time()
print(end_time-start_time)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104]
0.0001412629999961723


Numpy Array

In [46]:
import numpy as np
from time import process_time
np_array= np.array([i for i in range(100)])
print(np_array)
start_time=process_time()
np_array += 5
print(np_array)
end_time=process_time()
print(end_time-start_time)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[  5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22
  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40
  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94
  95  96  97  98  99 100 101 102 103 104]
0.0003894970000004605


**Numpy Arrays**

In [7]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [9]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

**Creating 1-D array**

In [10]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
a.shape

(4,)

**2-D array**

In [12]:
b=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(b)
b.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [13]:
b=np.array([(1,2,3),(4,5,6),(7,8,9)],dtype=float)
print(b)
b.shape

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


(3, 3)

Initial placeholders in numpy arrays

In [15]:
# create numpy arrays of zeroes
x=np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
x=np.zeros((4,5),dtype=int)
print(x)


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [17]:
y=np.ones((4,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
y=np.full((4,4),5)
print(y)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [19]:
# create an identity matrix
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
# create numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.91207322 0.51759731 0.92975304 0.94978145]
 [0.75340798 0.69903351 0.15920066 0.76906854]
 [0.07835486 0.98826583 0.49199221 0.18841542]]


In [21]:
# random integer values array
c=np.random.randint(1,100,(3,5))
print(c)

[[ 3 24 13 37 75]
 [33 20 85 54 43]
 [89 17 82 39 29]]


In [22]:
# array of evevnly spaced values --> specifying the number of values required
d=np.linspace(10,30,4)
print(d)

[10.         16.66666667 23.33333333 30.        ]


In [24]:
# array of evevnly spaced values --> specifying the step value
e=np.arange(10,30,4)
print(e)

[10 14 18 22 26]


In [25]:
#convert a list to numpy array
list2=[5,10,15,20]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[ 5 10 15 20]


numpy.ndarray

**Analysing a numpy array**

In [26]:
c=np.random.randint(1,100,(5,5))
print(c)

[[92 72 98  9 34]
 [74 72 15 40 32]
 [ 2 17 49  8 71]
 [21 71 11 95 65]
 [ 9 33 92 36  4]]


In [27]:
print(c.shape)

(5, 5)


In [28]:
print(c.ndim)

2


In [29]:
print(c.size)

25


In [30]:
print(c.dtype)

int64


Mathematical Operations on numpy array

In [31]:
List1=[1,2,3]
List2=[4,5,6]
print(List1+List2)

[1, 2, 3, 4, 5, 6]


In [32]:
a=np.asarray(List1)
b=np.asarray(List2)
print(a+b) # add two arrays


[5 7 9]


In [33]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [34]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 23 15]
 [13 22 15]
 [20 21 12]]
[[-10  -5  -9]
 [-13  -4 -13]
 [ -6 -11 -10]]
[[ 96 126  36]
 [  0 117  14]
 [ 91  80  11]]
[[0.375      0.64285714 0.25      ]
 [0.         0.69230769 0.07142857]
 [0.53846154 0.3125     0.09090909]]


In [35]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 23 15]
 [13 22 15]
 [20 21 12]]
[[-10  -5  -9]
 [-13  -4 -13]
 [ -6 -11 -10]]
[[ 96 126  36]
 [  0 117  14]
 [ 91  80  11]]
[[0.375      0.64285714 0.25      ]
 [0.         0.69230769 0.07142857]
 [0.53846154 0.3125     0.09090909]]


Array Manipulation

In [38]:
array=np.random.randint(0,20,(4,5))
print(array)
print(array.shape)

[[ 6  4  2  3  3]
 [ 4  9  4 14  5]
 [19 19  7 18 19]
 [14 18  7 16 11]]
(4, 5)


In [39]:
# Transpose
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[ 6  4 19 14]
 [ 4  9 19 18]
 [ 2  4  7  7]
 [ 3 14 18 16]
 [ 3  5 19 11]]
(5, 4)


In [40]:
array=np.random.randint(0,20,(4,5))
print(array)
print(array.shape)

[[14 16 15 18  3]
 [16  2  3 17 16]
 [13  0  5  8  6]
 [ 5 10 17 19  4]]
(4, 5)


In [42]:
trans=array.T
print(trans)
print(trans.shape)

[[14 16 13  5]
 [16  2  0 10]
 [15  3  5 17]
 [18 17  8 19]
 [ 3 16  6  4]]
(5, 4)


In [43]:
# reshaping an array
a=np.random.randint(0,30,(2,3))
print(a)
print(a.shape)

[[ 9  3  5]
 [14 23  9]]
(2, 3)


In [44]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[ 9  3]
 [ 5 14]
 [23  9]]
(3, 2)
